/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proye_Jazz;

import javax.swing.table.TableRowSorter;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;

public class BIBLIO_VIRTUAL extends javax.swing.JFrame {

    Usuarios usuarios[];
    Bibliografia biblio[];
    Login admin1 = new Login(usuarios,biblio);
    String texto;
    //verifica el llenado de los libros
    public static int contador=0;
    // mantiene el resultado en los libros
    public int contador2=0;
    
    
    

    private TableRowSorter trsfiltro;
    String filtro;
    
    int sel;
    int fila;
    
    public BIBLIO_VIRTUAL(Usuarios usuarios[],Bibliografia biblio[]) {
            this.usuarios = usuarios;
            this.biblio=biblio;

        initComponents();
        Cargar1();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        CAJA_BUSQUEDA = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nue_li = new javax.swing.JTable();
        nomb = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jButton1.setText("LOGOUT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        CAJA_BUSQUEDA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CAJA_BUSQUEDAActionPerformed(evt);
            }
        });
        CAJA_BUSQUEDA.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                CAJA_BUSQUEDAKeyTyped(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AUTOR", "AÑO", "TITULO", "DESCRIPCION", "PALABRAS", "EDICION", "TEMAS", "COPIAS", "AREA", "CATEGORIA", "ISBRI", " " }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton2.setText("REGRESAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("BUSCAR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("VER BIBLIOTECA VIRTUAL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setText("BIBLIOTECA VIRTUAL");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        nue_li.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AUTOR", "AÑO", "TITULO", "DESCRIPCION", "PALABRA", "EDICION", "TEMAS", "COPIAS", "AREAS", "CATEGORIA", "ISBRI", "TIPO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, true, true, true, true, true, true, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        nue_li.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nue_liMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(nue_li);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 74, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 69, Short.MAX_VALUE)
        );

        jButton5.setText("AGREGAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel2.setText("LIBROS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addComponent(nomb, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(34, 34, 34)
                                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(CAJA_BUSQUEDA, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 145, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(168, 168, 168)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(layout.createSequentialGroup()
                .addGap(360, 360, 360)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(nomb, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CAJA_BUSQUEDA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addGap(20, 20, 20)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CAJA_BUSQUEDAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CAJA_BUSQUEDAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CAJA_BUSQUEDAActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    System.out.println(usuarios[admin1.coordenada].getCon_li());
    biblio_libros admin5 = new biblio_libros(usuarios,biblio);
    admin5.setVisible(true);
        this.dispose();

        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            CAJA_BUSQUEDA.addKeyListener(new KeyAdapter(){

            @Override
            public void keyReleased(final KeyEvent e){
            String cadena = CAJA_BUSQUEDA.getText();
            CAJA_BUSQUEDA.setText(cadena);
            
            repaint();
            filtro();

}
});      
    }//GEN-LAST:event_jButton3ActionPerformed

    private void CAJA_BUSQUEDAKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_CAJA_BUSQUEDAKeyTyped
       
        trsfiltro =new TableRowSorter(nue_li.getModel());
        nue_li.setRowSorter(trsfiltro); 
      
    }//GEN-LAST:event_CAJA_BUSQUEDAKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     usuarios[admin1.coordenada].setCon_li(contador2);
           
    System.out.println(usuarios[admin1.coordenada].getLibro5());
    
    System.out.println(contador);     
    inicio_usu admin = new inicio_usu(usuarios,biblio);
    admin.setVisible(true);
    setVisible(false);
    this.dispose();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void nue_liMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nue_liMouseClicked
      //OBTIENE LOS DATOS DE MIS TABLAS Y CREA LOS LIBROS
        sel=nue_li.getSelectedRow();
        
        String a ;
        String b ;
        String c ;
        String d ;
        String e ;
        String f ;
        String g ;
        String h ;
        String k ;
        String l ;
        String m ;
        String n ;
        
                  
                
        a=nue_li.getValueAt(sel,0).toString();
        b=nue_li.getValueAt(sel,1).toString();
        c=nue_li.getValueAt(sel,2).toString();
        d=nue_li.getValueAt(sel,3).toString();
        e=nue_li.getValueAt(sel,4).toString();
        f=nue_li.getValueAt(sel,5).toString();
        g=nue_li.getValueAt(sel,6).toString();
        h=nue_li.getValueAt(sel,7).toString();
        k=nue_li.getValueAt(sel,8).toString();
        l=nue_li.getValueAt(sel,9).toString();
        m=nue_li.getValueAt(sel,10).toString();
        n=nue_li.getValueAt(sel,11).toString();
        
        fila=sel; 
        texto=" AUTOR "+a+" DE LA(EL) "+n+" TITULO "+c+" Y EDICION "+"\n"+f+", SE CREO EN EL AÑO "+b+" TEMAS PRINCIPALES "+g+"."+"\n"+" DESCRIPCION DEL LIBRO "+d; 
        
    }//GEN-LAST:event_nue_liMouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     contador++;
     
        if (contador==1) {
            contador2++;
             
                usuarios[admin1.coordenada].setLibro1(texto);
            
        }else{
        if (contador==2) {
            contador2++;
            usuarios[admin1.coordenada].setLibro2(texto);
     
        }else{
        if (contador==3) {
            contador2++;
            usuarios[admin1.coordenada].setLibro3(texto);

                
        }else{
        if (contador==4) {
            contador2++;
        usuarios[admin1.coordenada].setLibro4(texto);

    
        }else{
        if (contador==5) {
             contador2++;
        usuarios[admin1.coordenada].setLibro5(texto);
           
            
        }else{
         JOptionPane.showMessageDialog(this, "el limite es de 5 libros");   
        }
        }
        }
        }
        }
        //contador2=usuarios[admin1.coordenada].getCon_li();
        System.out.println(usuarios[admin1.coordenada].getCon_li());
        
        contador2=0;
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    public void filtro (){
        
  // filtra los datos de mi tabla
    String ele = (String) jComboBox1.getSelectedItem();
    
        if (ele=="AUTOR") {
           filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),0)); 
        }else{
            if (ele=="AÑO") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),1));
                
        }else{
            if (ele=="TITULO") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),2));
        }else{
            if (ele=="DESCRIPCION") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),3));
                        
        }else{
            if (ele=="PALABRAS") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),4));        
        }else{
            if (ele=="EDICION") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),5));    
                    
        }else{
            if (ele=="TEMAS") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),6));
                    
        }else{
            if (ele=="COPIAS") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),7));    
                    
        }else{
            if (ele=="AREA") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),8));    
                    
        }else{
            if (ele=="CATEGORIA") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),9));          
        }else{
            if (ele=="ISBRI") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),10));  
                    
        }else{
                if (ele=="TIPO") {
            filtro = CAJA_BUSQUEDA.getText();
            trsfiltro.setRowFilter(RowFilter.regexFilter(CAJA_BUSQUEDA.getText(),11)); 
                    
                }}}}}}}}}}}}}
    
    
    private void Cargar1(){
        //hace la carga para la tabla
        String datos [][] = new String[biblio.length][12];
        
        for (int i = 0; i < biblio.length; i++) {
            if (biblio [i] != null) {
                
                datos [i][0] = biblio[i].getAutor();
                datos [i][1] = biblio[i].getAño();
                datos [i][2] = biblio[i].getTitulo();
                datos [i][3] = biblio[i].getDescripcion();
                datos [i][4] = biblio[i].getPalabra();
                datos [i][5] = biblio[i].getEdicion();
                datos [i][6] = biblio[i].getTemas();
                datos [i][7] = biblio[i].getCoplas();
                datos [i][8] = biblio[i].getArea();
                datos [i][9] = biblio[i].getCategoria();
                datos [i][10] = biblio[i].getIsbn();
                datos [i][11] = biblio[i].getTipo();
               
                
            }
        }
        
        
        nue_li.setModel(new javax.swing.table.DefaultTableModel(
            datos,
            new String [] {
                "AUTOR","AÑO","TITULO","DESCRIPCION","PALABRAS","EDICION","AREA","TEMAS","COPIAS","CATEGORIA","ISBRI","TIPO"
            }
        ));
        
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CAJA_BUSQUEDA;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    public static javax.swing.JLabel nomb;
    public static javax.swing.JTable nue_li;
    // End of variables declaration//GEN-END:variables
}
