/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proye_Jazz;

/**
 *
 * @author Usuario
 */
public class REVISTA extends javax.swing.JFrame {

    Usuarios usuarios[];
    Bibliografia biblio[];
    TESIS_METO tesis_meto[];
    REVISTA_METO revista_meto[];
    DIGITAL_METO digital_meto[];
    
    String Re_Autor;
    String Re_Año;
    String Re_Titulo;
    String Re_Descripcion;
    String Re_Palabra;
    String Re_Edicion;
    String Re_Temas;
    String Re_Coplas;
    String Re_Area;
    String Re_Categoria;
    String Re_Isbn;
    
    int sel;
    int fila;
    
    public REVISTA(Usuarios usuarios[],Bibliografia biblio[],TESIS_METO tesis_meto[],REVISTA_METO revista_meto[],DIGITAL_METO digital_meto[]) {
        this.usuarios = usuarios;
        this.biblio=biblio;
        this.tesis_meto=tesis_meto;
        this.revista_meto=revista_meto;
        this.digital_meto=digital_meto;
        
        initComponents();
        Cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_copias = new javax.swing.JTextField();
        txt_temas = new javax.swing.JTextField();
        txt_area = new javax.swing.JTextField();
        txt_isbri = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_revista = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txt_descrip = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        txt_año = new javax.swing.JTextField();
        txt_autor = new javax.swing.JTextField();
        txt_palabras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_edicion = new javax.swing.JTextField();
        txt_categoria = new javax.swing.JTextField();
        B_IN = new javax.swing.JButton();
        B_MOD = new javax.swing.JButton();
        B_ELI = new javax.swing.JButton();
        B_GUARDAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_isbri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_isbriActionPerformed(evt);
            }
        });

        tabla_revista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AUTOR", "AÑO", "TITULO", "DESCRIPCION", "PALABRAS", "EDICION", "AREA", "TEMAS", "COPIAS", "CATEGORIA", "ISBRI"
            }
        ));
        tabla_revista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabla_revistaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla_revista);

        jLabel13.setText("REVISTA");

        jLabel9.setText("COPIAS");

        jLabel10.setText("AREA");

        jLabel11.setText("CATEGORIA");

        jLabel12.setText("ISBRI");

        txt_año.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_añoActionPerformed(evt);
            }
        });

        txt_palabras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_palabrasActionPerformed(evt);
            }
        });

        jLabel2.setText("AUTOR");

        jLabel3.setText("AÑO");

        jLabel4.setText("TITULO");

        jLabel5.setText("DESCRIPCION");

        jLabel6.setText("PALABRAS");

        jLabel7.setText("EDICION");

        jLabel8.setText("TEMAS");

        B_IN.setText("INSERTAR");
        B_IN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_INActionPerformed(evt);
            }
        });

        B_MOD.setText("MODIFICAR");
        B_MOD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_MODActionPerformed(evt);
            }
        });

        B_ELI.setText("ELIMINAR");

        B_GUARDAR.setText("GUARDAR Y SALIR");
        B_GUARDAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B_GUARDARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(366, 366, 366)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(B_GUARDAR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_ELI, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_MOD, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(B_IN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(394, 394, 394)
                        .addComponent(jLabel13)))
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_descrip, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(txt_titulo)
                                .addComponent(txt_año)
                                .addComponent(txt_autor)
                                .addComponent(txt_palabras)
                                .addComponent(txt_edicion))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_categoria)
                                .addComponent(txt_copias)
                                .addComponent(txt_temas)
                                .addComponent(txt_area)
                                .addComponent(txt_isbri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(43, 43, 43)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(35, 35, 35)
                .addComponent(B_IN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_MOD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_ELI)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(B_GUARDAR)
                .addContainerGap(358, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(txt_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txt_temas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txt_copias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txt_descrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txt_palabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(txt_isbri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 313, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_añoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_añoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_añoActionPerformed

    private void txt_palabrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_palabrasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_palabrasActionPerformed

    private void txt_isbriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_isbriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_isbriActionPerformed

    private void B_GUARDARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_GUARDARActionPerformed
       
        Administrador admin = new Administrador(usuarios,biblio,tesis_meto,revista_meto,digital_meto);
        admin.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_B_GUARDARActionPerformed

    private void B_INActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_INActionPerformed
       
    Re_Autor=txt_autor.getText();
    Re_Año=txt_año.getText();
    Re_Titulo=txt_titulo.getText();
    Re_Descripcion=txt_descrip.getText();
    Re_Palabra=txt_palabras.getText();
    Re_Edicion=txt_edicion.getText();
    Re_Temas=txt_temas.getText();
    Re_Coplas=txt_copias.getText();
    Re_Area=txt_area.getText();
    Re_Categoria=txt_categoria.getText();
    Re_Isbn=txt_isbri.getText();
        
    revista_meto [Proye_Jazz.contador1] = new REVISTA_METO(Re_Autor, Re_Año,Re_Titulo, Re_Descripcion, Re_Palabra,Re_Edicion,Re_Temas,Re_Coplas,Re_Area,Re_Categoria,Re_Isbn);
    Proye_Jazz.contador1 ++;    
    
    
        txt_autor.setText("");
        txt_año.setText("");
        txt_titulo.setText("");
        txt_descrip.setText("");
        txt_palabras.setText("");
        txt_edicion.setText("");
        txt_temas.setText("");
        txt_copias.setText("");
        txt_area.setText("");
        txt_categoria.setText("");
        txt_isbri.setText("");    
        
        
        
    }//GEN-LAST:event_B_INActionPerformed

    private void B_MODActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B_MODActionPerformed
    Re_Autor=txt_autor.getText();
    Re_Año=txt_año.getText();
    Re_Titulo=txt_titulo.getText();
    Re_Descripcion=txt_descrip.getText();
    Re_Palabra=txt_palabras.getText();
    Re_Edicion=txt_edicion.getText();
    Re_Temas=txt_temas.getText();
    Re_Coplas=txt_copias.getText();
    Re_Area=txt_area.getText();
    Re_Categoria=txt_categoria.getText();
    Re_Isbn=txt_isbri.getText();
        
    revista_meto [sel] = new REVISTA_METO(Re_Autor, Re_Año,Re_Titulo, Re_Descripcion, Re_Palabra,Re_Edicion,Re_Temas,Re_Coplas,Re_Area,Re_Categoria,Re_Isbn);
        
        for (int i = 0; i < tabla_revista.getColumnCount(); i++) {
            
          tabla_revista.setValueAt(revista_meto[i], fila, i);
 
        }
        
        txt_autor.setText("");
        txt_año.setText("");
        txt_titulo.setText("");
        txt_descrip.setText("");
        txt_palabras.setText("");
        txt_edicion.setText("");
        txt_temas.setText("");
        txt_copias.setText("");
        txt_area.setText("");
        txt_categoria.setText("");
        txt_isbri.setText("");
        
        
    }//GEN-LAST:event_B_MODActionPerformed

    private void tabla_revistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabla_revistaMouseClicked
       sel=tabla_revista.getSelectedRow();
        
        
        txt_autor.setText(tabla_revista.getValueAt(sel,0).toString());
        txt_año.setText(tabla_revista.getValueAt(sel,1).toString());
        txt_titulo.setText(tabla_revista.getValueAt(sel,2).toString());
        txt_descrip.setText(tabla_revista.getValueAt(sel,3).toString());
        txt_palabras.setText(tabla_revista.getValueAt(sel,4).toString());
        txt_edicion.setText(tabla_revista.getValueAt(sel,5).toString());
        txt_temas.setText(tabla_revista.getValueAt(sel,6).toString());
        txt_copias.setText(tabla_revista.getValueAt(sel,7).toString());
        txt_area.setText(tabla_revista.getValueAt(sel,8).toString());
        txt_categoria.setText(tabla_revista.getValueAt(sel,9).toString());
        txt_isbri.setText(tabla_revista.getValueAt(sel,10).toString());
        
        
        fila=sel;
    }//GEN-LAST:event_tabla_revistaMouseClicked

    private void Cargar(){
        
        String datos [][] = new String[revista_meto.length][11];
        
        for (int i = 0; i < revista_meto.length; i++) {
            if (revista_meto [i] != null) {
                
                datos [i][0] = revista_meto[i].getR_Autor();
                datos [i][1] = revista_meto[i].getR_Año();
                datos [i][2] = revista_meto[i].getR_Titulo();
                datos [i][3] = revista_meto[i].getR_Descripcion();
                datos [i][4] = revista_meto[i].getR_Palabra();
                datos [i][5] = revista_meto[i].getR_Edicion();
                datos [i][6] = revista_meto[i].getR_Temas();
                datos [i][7] = revista_meto[i].getR_Coplas();
                datos [i][8] = revista_meto[i].getR_Area();
                datos [i][9] = revista_meto[i].getR_Categoria();
                datos [i][10] = revista_meto[i].getR_Isbn();
               
                
            }
        }
        
        tabla_revista.setModel(new javax.swing.table.DefaultTableModel(
            datos,
            new String [] {
                "AUTOR","AÑO","TITULO","DESCRIPCION","PALABRAS","EDICION","AREA","TEMAS","COPIAS","CATEGORIA","ISBRI,"
            }
        ));
        
    }
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B_ELI;
    private javax.swing.JButton B_GUARDAR;
    private javax.swing.JButton B_IN;
    private javax.swing.JButton B_MOD;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla_revista;
    private javax.swing.JTextField txt_area;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_categoria;
    private javax.swing.JTextField txt_copias;
    private javax.swing.JTextField txt_descrip;
    private javax.swing.JTextField txt_edicion;
    private javax.swing.JTextField txt_isbri;
    private javax.swing.JTextField txt_palabras;
    private javax.swing.JTextField txt_temas;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
