/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Proye_Jazz;

/**
 *
 * @author Usuario
 */
public class TESIS extends javax.swing.JFrame {

    Usuarios usuarios[];
    Bibliografia biblio[];
    TESIS_METO tesis_meto[];
    REVISTA_METO revista_meto[];
    DIGITAL_METO digital_meto[];
    
    String TE_Autor;
    String TE_Año;
    String TE_Titulo;
    String TE_Descripcion;
    String TE_Palabra;
    String TE_Edicion;
    String TE_Temas;
    String TE_Coplas;
    String TE_Area;
    String TE_Categoria;
    String TE_Isbn;
    
    int sel;
    int fila;
    
    
    public TESIS(Usuarios usuarios[],Bibliografia biblio[],TESIS_METO tesis_meto[],REVISTA_METO revista_meto[],DIGITAL_METO digital_meto[]) {
        this.usuarios = usuarios;
        this.biblio=biblio;
        this.tesis_meto=tesis_meto;
        this.revista_meto=revista_meto;
        this.digital_meto=digital_meto;
        initComponents();
        Cargar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_isbri = new javax.swing.JTextField();
        txt_autor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TABLAS_TESIS = new javax.swing.JTable();
        txt_palabras = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_copias = new javax.swing.JTextField();
        txt_descrip = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_temas = new javax.swing.JTextField();
        txt_titulo = new javax.swing.JTextField();
        txt_edicion = new javax.swing.JTextField();
        txt_area = new javax.swing.JTextField();
        txt_año = new javax.swing.JTextField();
        txt_categoria = new javax.swing.JTextField();
        inser = new javax.swing.JButton();
        mod = new javax.swing.JButton();
        elimi = new javax.swing.JButton();
        guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TABLAS_TESIS.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AUTOR", "AÑO", "TITULO", "DESCRIPCION", "PALABRAS", "EDICION", "AREA", "TEMAS", "COPIAS", "CATEGORIA", "ISBRI"
            }
        ));
        TABLAS_TESIS.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TABLAS_TESISMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TABLAS_TESIS);

        jLabel2.setText("AUTOR");

        jLabel13.setText("TESIS");

        jLabel3.setText("AÑO");

        jLabel9.setText("COPIAS");

        jLabel4.setText("TITULO");

        jLabel10.setText("AREA");

        jLabel5.setText("DESCRIPCION");

        jLabel11.setText("CATEGORIA");

        jLabel6.setText("PALABRAS");

        jLabel12.setText("ISBRI");

        jLabel7.setText("EDICION");

        txt_copias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_copiasActionPerformed(evt);
            }
        });

        txt_descrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_descripActionPerformed(evt);
            }
        });

        jLabel8.setText("TEMAS");

        txt_temas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_temasActionPerformed(evt);
            }
        });

        txt_area.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_areaActionPerformed(evt);
            }
        });

        txt_categoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_categoriaActionPerformed(evt);
            }
        });

        inser.setText("INSERTAR");
        inser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserActionPerformed(evt);
            }
        });

        mod.setText("MODIFICAR");
        mod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modActionPerformed(evt);
            }
        });

        elimi.setText("ELIMINAR");
        elimi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                elimiActionPerformed(evt);
            }
        });

        guardar.setText("GUARDAR Y SALIR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(guardar)
                    .addComponent(mod, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elimi, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(352, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5)
                                .addComponent(jLabel4)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel6)
                                .addComponent(jLabel7))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_descrip, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                                .addComponent(txt_titulo)
                                .addComponent(txt_año)
                                .addComponent(txt_autor)
                                .addComponent(txt_palabras)
                                .addComponent(txt_edicion))
                            .addGap(166, 166, 166)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel11)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8)
                                .addComponent(jLabel10)
                                .addComponent(jLabel12))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_categoria)
                                .addComponent(txt_copias)
                                .addComponent(txt_temas)
                                .addComponent(txt_area)
                                .addComponent(txt_isbri, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(43, 43, 43)))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(inser)
                .addGap(18, 18, 18)
                .addComponent(mod, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(elimi)
                .addGap(18, 18, 18)
                .addComponent(guardar)
                .addContainerGap(260, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(txt_autor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel10)
                                .addComponent(txt_area, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txt_año, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel8)
                                .addComponent(txt_temas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(txt_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(txt_copias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(txt_descrip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(txt_categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(txt_palabras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel12)
                                .addComponent(txt_isbri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(jLabel13))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(txt_edicion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
     Administrador admin = new Administrador(usuarios,biblio,tesis_meto,revista_meto,digital_meto);
        admin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_guardarActionPerformed

    private void inserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserActionPerformed
    TE_Autor=txt_autor.getText();
    TE_Año=txt_año.getText();
    TE_Titulo=txt_titulo.getText();
    TE_Descripcion=txt_descrip.getText();
    TE_Palabra=txt_palabras.getText();
    TE_Edicion=txt_edicion.getText();
    TE_Temas=txt_temas.getText();
    TE_Coplas=txt_copias.getText();
    TE_Area=txt_area.getText();
    TE_Categoria=txt_categoria.getText();
    TE_Isbn=txt_isbri.getText();
        
    tesis_meto [Proye_Jazz.contador1] = new TESIS_METO(TE_Autor, TE_Año,TE_Titulo, TE_Descripcion, TE_Palabra,TE_Edicion,TE_Temas,TE_Coplas,TE_Area,TE_Categoria,TE_Isbn);
    
    Proye_Jazz.contador1 ++;    
    
    
        txt_autor.setText("");
        txt_año.setText("");
        txt_titulo.setText("");
        txt_descrip.setText("");
        txt_palabras.setText("");
        txt_edicion.setText("");
        txt_temas.setText("");
        txt_copias.setText("");
        txt_area.setText("");
        txt_categoria.setText("");
        txt_isbri.setText(""); 
    }//GEN-LAST:event_inserActionPerformed

    private void txt_descripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_descripActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_descripActionPerformed

    private void txt_areaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_areaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_areaActionPerformed

    private void txt_temasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_temasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_temasActionPerformed

    private void txt_copiasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_copiasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_copiasActionPerformed

    private void txt_categoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_categoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_categoriaActionPerformed

    private void modActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modActionPerformed
    TE_Autor=txt_autor.getText();
    TE_Año=txt_año.getText();
    TE_Titulo=txt_titulo.getText();
    TE_Descripcion=txt_descrip.getText();
    TE_Palabra=txt_palabras.getText();
    TE_Edicion=txt_edicion.getText();
    TE_Temas=txt_temas.getText();
    TE_Coplas=txt_copias.getText();
    TE_Area=txt_area.getText();
    TE_Categoria=txt_categoria.getText();
    TE_Isbn=txt_isbri.getText();
        
    tesis_meto [sel] = new TESIS_METO(TE_Autor, TE_Año,TE_Titulo, TE_Descripcion, TE_Palabra,TE_Edicion,TE_Temas,TE_Coplas,TE_Area,TE_Categoria,TE_Isbn);
    
        for (int i = 0; i < TABLAS_TESIS.getColumnCount(); i++) {
            
          TABLAS_TESIS.setValueAt(tesis_meto[i], fila, i);
 
        }
        
        txt_autor.setText("");
        txt_año.setText("");
        txt_titulo.setText("");
        txt_descrip.setText("");
        txt_palabras.setText("");
        txt_edicion.setText("");
        txt_temas.setText("");
        txt_copias.setText("");
        txt_area.setText("");
        txt_categoria.setText("");
        txt_isbri.setText("");
        
       
    }//GEN-LAST:event_modActionPerformed

    private void elimiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_elimiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_elimiActionPerformed

    private void TABLAS_TESISMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TABLAS_TESISMouseClicked
     
        sel=TABLAS_TESIS.getSelectedRow();
        
        
        txt_autor.setText(TABLAS_TESIS.getValueAt(sel,0).toString());
        txt_año.setText(TABLAS_TESIS.getValueAt(sel,1).toString());
        txt_titulo.setText(TABLAS_TESIS.getValueAt(sel,2).toString());
        txt_descrip.setText(TABLAS_TESIS.getValueAt(sel,3).toString());
        txt_palabras.setText(TABLAS_TESIS.getValueAt(sel,4).toString());
        txt_edicion.setText(TABLAS_TESIS.getValueAt(sel,5).toString());
        txt_temas.setText(TABLAS_TESIS.getValueAt(sel,6).toString());
        txt_copias.setText(TABLAS_TESIS.getValueAt(sel,7).toString());
        txt_area.setText(TABLAS_TESIS.getValueAt(sel,8).toString());
        txt_categoria.setText(TABLAS_TESIS.getValueAt(sel,9).toString());
        txt_isbri.setText(TABLAS_TESIS.getValueAt(sel,10).toString());
        
        
        fila=sel;
        
        
        
        
    }//GEN-LAST:event_TABLAS_TESISMouseClicked

    
    private void Cargar(){
        
        String datos [][] = new String[tesis_meto.length][11];
        
        for (int i = 0; i < tesis_meto.length; i++) {
            if (tesis_meto [i] != null) {
                
                datos [i][0] = tesis_meto[i].getTE_Autor();
                datos [i][1] = tesis_meto[i].getTE_Año();
                datos [i][2] = tesis_meto[i].getTE_Titulo();
                datos [i][3] = tesis_meto[i].getTE_Descripcion();
                datos [i][4] = tesis_meto[i].getTE_Palabra();
                datos [i][5] = tesis_meto[i].getTE_Edicion();
                datos [i][6] = tesis_meto[i].getTE_Temas();
                datos [i][7] = tesis_meto[i].getTE_Coplas();
                datos [i][8] = tesis_meto[i].getTE_Area();
                datos [i][9] = tesis_meto[i].getTE_Categoria();
                datos [i][10] = tesis_meto[i].getTE_Isbn();
               
                
            }
        }
        
        TABLAS_TESIS.setModel(new javax.swing.table.DefaultTableModel(
            datos,
            new String [] {
                "AUTOR","AÑO","TITULO","DESCRIPCION","PALABRAS","EDICION","AREA","TEMAS","COPIAS","CATEGORIA","ISBRI,"
            }
        ));
        
    }
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TABLAS_TESIS;
    private javax.swing.JButton elimi;
    private javax.swing.JButton guardar;
    private javax.swing.JButton inser;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mod;
    private javax.swing.JTextField txt_area;
    private javax.swing.JTextField txt_autor;
    private javax.swing.JTextField txt_año;
    private javax.swing.JTextField txt_categoria;
    private javax.swing.JTextField txt_copias;
    private javax.swing.JTextField txt_descrip;
    private javax.swing.JTextField txt_edicion;
    private javax.swing.JTextField txt_isbri;
    private javax.swing.JTextField txt_palabras;
    private javax.swing.JTextField txt_temas;
    private javax.swing.JTextField txt_titulo;
    // End of variables declaration//GEN-END:variables
}
